channels:
  - conda-forge
dependencies:
  - python =3.14
  - heyoka.py =7.11.*
  - pykep
  - matplotlib
  - sympy
  - scipy
  - ipympl
  - tqdm
  - cloudpickle
  - astroquery
  - skyfield
  - cartopy
  - sgp4
